# build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11.0.3
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.3

      - name: setup dependencies
        run: sudo apt-get install libxml2-utils

      - name: mvn-build
        run: make install

      - name: debug
        run: echo ${{ steps.mvn-build.outputs.zip_output_path }}

      - name: Upload mvn zip artifact
        uses: actions/upload-artifact@v1
        with:
          name: zip_output_path
          path: target/SimpleSlackWebhookClient-1.0-SNAPSHOT.zip
#          path: ${{ steps.mvn-build.outputs.zip_output_path }}
